// GENERATED by scripts/gen-param-docs.mjs — do not edit by hand.
// Metadata for every Planet parameter: domain (planet | gas | star),
// studio group / label, type, default, slider range and description.
export const PARAM_DOCS = {
  "mode": {
    "domain": "planet",
    "group": "General",
    "label": "mode",
    "type": "string",
    "default": "planet",
    "description": "Body type: 'planet' (terrestrial), 'gas' or 'star'. Prefer the Planet `type` option."
  },
  "renderVersion": {
    "domain": "planet",
    "group": "General",
    "label": "renderVersion",
    "type": "number",
    "default": 3,
    "description": "Look-model version of the parameter set (used to migrate old studio projects). Leave as is."
  },
  "starTemperature": {
    "domain": "star",
    "group": "Photosphere",
    "label": "Temperature",
    "type": "number",
    "default": 5772,
    "description": "Effective temperature (K) — the Sun",
    "min": 2000,
    "max": 30000,
    "step": 100
  },
  "starTint": {
    "domain": "star",
    "group": "Colors",
    "label": "Tint",
    "type": "color",
    "default": [
      1,
      0.98,
      0.7
    ],
    "description": "Artistic filter over the blackbody colour: a real 5772 K disc is a pale peach-white on screen; this warms it toward the familiar golden Sun"
  },
  "starBrightness": {
    "domain": "star",
    "group": "Photosphere",
    "label": "Brightness",
    "type": "number",
    "default": 1,
    "description": "Emitted radiance (drives glare / bloom)",
    "min": 0.2,
    "max": 5,
    "step": 0.05
  },
  "starNoiseScale": {
    "domain": "star",
    "group": "Convection",
    "label": "Granule scale",
    "type": "number",
    "default": 3,
    "description": "Granulation scale — Size of the convection cells (larger = smaller cells)",
    "min": 0.5,
    "max": 8,
    "step": 0.1
  },
  "starTurbulence": {
    "domain": "star",
    "group": "Convection",
    "label": "Network",
    "type": "number",
    "default": 0.6,
    "description": "Supergranulation network / mottling",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "starGranules": {
    "domain": "star",
    "group": "Convection",
    "label": "Granulation",
    "type": "number",
    "default": 0.9,
    "description": "Granulation contrast — Contrast between bright cells and dark lanes",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "starFlowSpeed": {
    "domain": "star",
    "group": "Convection",
    "label": "Flow speed",
    "type": "number",
    "default": 1,
    "description": "Convection + rotation speed",
    "min": 0,
    "max": 3,
    "step": 0.05
  },
  "starFaculae": {
    "domain": "star",
    "group": "Convection",
    "label": "Faculae",
    "type": "number",
    "default": 0.8,
    "description": "Bright network toward the limb — Bright magnetic network, strongest toward the limb",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "starSpotsEnabled": {
    "domain": "star",
    "group": "Sunspots",
    "label": "Sunspots",
    "type": "boolean",
    "default": true,
    "description": "Render sunspots."
  },
  "starSpots": {
    "domain": "star",
    "group": "Sunspots",
    "label": "Amount",
    "type": "number",
    "default": 0.4,
    "description": "Sunspot coverage — Magnetic activity: spot coverage in the active belts",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "starSpotScale": {
    "domain": "star",
    "group": "Sunspots",
    "label": "Region size",
    "type": "number",
    "default": 2.4,
    "description": "Active-region size (frequency) — Frequency of the active regions (larger = smaller groups)",
    "min": 0.5,
    "max": 8,
    "step": 0.1
  },
  "starLimbDarken": {
    "domain": "star",
    "group": "Photosphere",
    "label": "Limb darkening",
    "type": "number",
    "default": 1,
    "description": "1 = solar limb darkening — 1 = solar; the limb also reddens",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "starBloom": {
    "domain": "star",
    "group": "Glare",
    "label": "Bloom",
    "type": "number",
    "default": 1,
    "description": "Glare / bloom strength — Glare spreading from the overexposed disc",
    "min": 0,
    "max": 3,
    "step": 0.05
  },
  "starPulseAmount": {
    "domain": "star",
    "group": "Motion",
    "label": "Pulse amount",
    "type": "number",
    "default": 0,
    "description": "Radius breathing (pulsating variables)",
    "min": 0,
    "max": 0.08,
    "step": 0.002
  },
  "starPulseSpeed": {
    "domain": "star",
    "group": "Motion",
    "label": "Pulse speed",
    "type": "number",
    "default": 1.2,
    "description": "Speed of the radius breathing (starPulseAmount).",
    "min": 0,
    "max": 4,
    "step": 0.1
  },
  "starCoronaEnabled": {
    "domain": "star",
    "group": "Corona",
    "label": "Corona",
    "type": "boolean",
    "default": true,
    "description": "Render the corona / streamers around the disc."
  },
  "starCoronaColor": {
    "domain": "star",
    "group": "Colors",
    "label": "Corona",
    "type": "color",
    "default": [
      1,
      0.94,
      0.86
    ],
    "description": "Corona"
  },
  "starCoronaSize": {
    "domain": "star",
    "group": "Corona",
    "label": "Size",
    "type": "number",
    "default": 0.6,
    "description": "Halo extent (fraction of radius) — Extent of the outer corona",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "starCoronaStrength": {
    "domain": "star",
    "group": "Corona",
    "label": "Strength",
    "type": "number",
    "default": 0.6,
    "description": "Strength",
    "min": 0,
    "max": 2,
    "step": 0.05
  },
  "starFlares": {
    "domain": "star",
    "group": "Corona",
    "label": "Streamers",
    "type": "number",
    "default": 0.7,
    "description": "Streamer contrast in the corona — Contrast of the radial streamers",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "starProminences": {
    "domain": "star",
    "group": "Limb",
    "label": "Prominences",
    "type": "number",
    "default": 0.5,
    "description": "Limb prominences — Glowing plasma loops rising off the limb",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "starChromoColor": {
    "domain": "star",
    "group": "Colors",
    "label": "Chromosphere",
    "type": "color",
    "default": [
      1,
      0.3,
      0.22
    ],
    "description": "H-alpha chromosphere / prominences"
  },
  "gasBandCount": {
    "domain": "gas",
    "group": "Bands",
    "label": "Band count",
    "type": "number",
    "default": 18,
    "description": "Belts + zones, pole to pole",
    "min": 2,
    "max": 32,
    "step": 1
  },
  "gasContrast": {
    "domain": "gas",
    "group": "Bands",
    "label": "Contrast",
    "type": "number",
    "default": 0.6,
    "description": "Belt / zone contrast — Brightness difference between dark belts and bright zones",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "gasBandWarp": {
    "domain": "gas",
    "group": "Bands",
    "label": "Waviness",
    "type": "number",
    "default": 0.5,
    "description": "Band edge waviness — How much the band edges meander",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "gasWarp": {
    "domain": "gas",
    "group": "Flow",
    "label": "Turbulence",
    "type": "number",
    "default": 0.75,
    "description": "Eddy turbulence in the shear zones — Eddies in the shear zones between belts and zones",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "gasScale": {
    "domain": "gas",
    "group": "Flow",
    "label": "Eddy scale",
    "type": "number",
    "default": 3,
    "description": "Eddy size (frequency) — Frequency of the turbulent eddies",
    "min": 0.8,
    "max": 8,
    "step": 0.1
  },
  "gasFlowSpeed": {
    "domain": "gas",
    "group": "Flow",
    "label": "Flow speed",
    "type": "number",
    "default": 1,
    "description": "Jet + churn speed — Zonal jet + churn speed",
    "min": 0,
    "max": 3,
    "step": 0.05
  },
  "gasPolarHaze": {
    "domain": "gas",
    "group": "Bands",
    "label": "Polar haze",
    "type": "number",
    "default": 0.55,
    "description": "Polar region extent / haze — Banding dissolves into cyclones under a haze toward the poles",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "gasLimb": {
    "domain": "gas",
    "group": "Body",
    "label": "Limb darkening",
    "type": "number",
    "default": 0.5,
    "description": "Minnaert limb darkening",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "gasTilt": {
    "domain": "gas",
    "group": "Body",
    "label": "Axial tilt",
    "type": "number",
    "default": 8,
    "description": "Axial tilt (degrees) — Tilt of the spin axis (and the ring plane), degrees",
    "min": 0,
    "max": 90,
    "step": 0.5
  },
  "gasStormsEnabled": {
    "domain": "gas",
    "group": "Storms",
    "label": "Storms",
    "type": "boolean",
    "default": true,
    "description": "Render the great spot and the small storm ovals."
  },
  "gasGreatSpot": {
    "domain": "gas",
    "group": "Storms",
    "label": "Great spot",
    "type": "number",
    "default": 0.65,
    "description": "Great storm size (0 = none) — Size of the giant anticyclone (0 = none)",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "gasStorms": {
    "domain": "gas",
    "group": "Storms",
    "label": "Oval count",
    "type": "number",
    "default": 0.5,
    "description": "Small oval count — Number of smaller vortices (white ovals, dark barges)",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "gasStormScale": {
    "domain": "gas",
    "group": "Storms",
    "label": "Oval size",
    "type": "number",
    "default": 1,
    "description": "Small oval size",
    "min": 0.3,
    "max": 3,
    "step": 0.05
  },
  "gasColorZone": {
    "domain": "gas",
    "group": "Cloud colors",
    "label": "Zones",
    "type": "color",
    "default": [
      0.82,
      0.74,
      0.6
    ],
    "description": "Bright zone colour (sRGB albedo)."
  },
  "gasColorBelt": {
    "domain": "gas",
    "group": "Cloud colors",
    "label": "Belts",
    "type": "color",
    "default": [
      0.56,
      0.4,
      0.29
    ],
    "description": "Dark belt colour (sRGB albedo)."
  },
  "gasColorAccent": {
    "domain": "gas",
    "group": "Cloud colors",
    "label": "Accent",
    "type": "color",
    "default": [
      0.68,
      0.38,
      0.23
    ],
    "description": "Turbulent eddy accent colour (sRGB albedo)."
  },
  "gasColorStorm": {
    "domain": "gas",
    "group": "Cloud colors",
    "label": "Great spot",
    "type": "color",
    "default": [
      0.7,
      0.33,
      0.2
    ],
    "description": "Storm / great spot colour (sRGB albedo)."
  },
  "gasColorPolar": {
    "domain": "gas",
    "group": "Cloud colors",
    "label": "Polar haze",
    "type": "color",
    "default": [
      0.52,
      0.53,
      0.56
    ],
    "description": "Polar region colour (sRGB albedo)."
  },
  "gasAtmoColor": {
    "domain": "gas",
    "group": "Atmosphere",
    "label": "Scattering tint",
    "type": "color",
    "default": [
      0.55,
      0.68,
      1
    ],
    "description": "High haze Rayleigh tint"
  },
  "gasAtmoStrength": {
    "domain": "gas",
    "group": "Atmosphere",
    "label": "Density",
    "type": "number",
    "default": 0.15,
    "description": "Air above the cloud tops",
    "min": 0,
    "max": 2,
    "step": 0.05
  },
  "gasAtmoHaze": {
    "domain": "gas",
    "group": "Atmosphere",
    "label": "Haze",
    "type": "number",
    "default": 0.5,
    "description": "Aerosol haze (Mie)",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "gasRingsEnabled": {
    "domain": "gas",
    "group": "Rings",
    "label": "Rings",
    "type": "boolean",
    "default": false,
    "description": "Render the ring system."
  },
  "gasRingInner": {
    "domain": "gas",
    "group": "Rings",
    "label": "Inner radius",
    "type": "number",
    "default": 1.25,
    "description": "X radius — Inner edge, in planet radii",
    "min": 1.05,
    "max": 3,
    "step": 0.01
  },
  "gasRingOuter": {
    "domain": "gas",
    "group": "Rings",
    "label": "Outer radius",
    "type": "number",
    "default": 2.25,
    "description": "Outer edge, in planet radii",
    "min": 1.2,
    "max": 4,
    "step": 0.01
  },
  "gasRingOpacity": {
    "domain": "gas",
    "group": "Rings",
    "label": "Opacity",
    "type": "number",
    "default": 1,
    "description": "Optical depth scale",
    "min": 0,
    "max": 2,
    "step": 0.02
  },
  "gasRingColor": {
    "domain": "gas",
    "group": "Rings",
    "label": "Color",
    "type": "color",
    "default": [
      0.86,
      0.8,
      0.69
    ],
    "description": "Ring particle colour (sRGB albedo)."
  },
  "seed": {
    "domain": "planet",
    "group": "General",
    "label": "seed",
    "type": "number",
    "default": 1337,
    "description": "Random seed: every procedural field (terrain, clouds, bands, spots) derives from it."
  },
  "radius": {
    "domain": "planet",
    "group": "Planet",
    "label": "Radius",
    "type": "number",
    "default": 2000,
    "description": "Planet radius in local units (world units at scale 1).",
    "min": 600,
    "max": 6000,
    "step": 50
  },
  "heightScale": {
    "domain": "planet",
    "group": "Planet",
    "label": "Height scale",
    "type": "number",
    "default": 80,
    "description": "Terrain relief: height of the highest peaks above the base radius, in local units.",
    "min": 20,
    "max": 400,
    "step": 5
  },
  "seaLevel": {
    "domain": "planet",
    "group": "Planet",
    "label": "Sea level",
    "type": "number",
    "default": 0.42,
    "description": "Sea level, as a fraction of heightScale above the base radius.",
    "min": 0,
    "max": 0.9,
    "step": 0.01
  },
  "noiseScale": {
    "domain": "planet",
    "group": "Noise",
    "label": "Scale",
    "type": "number",
    "default": 2.6,
    "description": "Base frequency of the continent noise (higher = more, smaller landmasses).",
    "min": 0.5,
    "max": 8,
    "step": 0.1
  },
  "octaves": {
    "domain": "planet",
    "group": "Noise",
    "label": "Octaves",
    "type": "number",
    "default": 6,
    "description": "Compile-time define (material rebuild) — Rebuilds the shaders",
    "min": 3,
    "max": 8,
    "step": 1,
    "structural": true
  },
  "persistence": {
    "domain": "planet",
    "group": "Noise",
    "label": "Persistence",
    "type": "number",
    "default": 0.52,
    "description": "Amplitude falloff between noise octaves (higher = rougher terrain).",
    "min": 0.3,
    "max": 0.7,
    "step": 0.01
  },
  "lacunarity": {
    "domain": "planet",
    "group": "Noise",
    "label": "Lacunarity",
    "type": "number",
    "default": 2.05,
    "description": "Frequency step between noise octaves.",
    "min": 1.5,
    "max": 3,
    "step": 0.05
  },
  "warp": {
    "domain": "planet",
    "group": "Noise",
    "label": "Warp",
    "type": "number",
    "default": 0.65,
    "description": "Domain warp strength: folds and twists coastlines and ranges.",
    "min": 0,
    "max": 2,
    "step": 0.05
  },
  "ridge": {
    "domain": "planet",
    "group": "Mountains & craters",
    "label": "Ridge",
    "type": "number",
    "default": 0.55,
    "description": "Strength of the ridged mountain ranges along tectonic belts.",
    "min": 0,
    "max": 1.5,
    "step": 0.05
  },
  "mountainScale": {
    "domain": "planet",
    "group": "Mountains & craters",
    "label": "Ridge scale",
    "type": "number",
    "default": 2.4,
    "description": "Frequency of the mountain ridges.",
    "min": 1,
    "max": 6,
    "step": 0.1
  },
  "craters": {
    "domain": "planet",
    "group": "Mountains & craters",
    "label": "Craters",
    "type": "number",
    "default": 0,
    "description": "Impact crater amount (0 = none).",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "craterScale": {
    "domain": "planet",
    "group": "Mountains & craters",
    "label": "Crater scale",
    "type": "number",
    "default": 6,
    "description": "Crater frequency (higher = smaller craters).",
    "min": 2,
    "max": 16,
    "step": 0.5
  },
  "continents": {
    "domain": "planet",
    "group": "Noise",
    "label": "Continents",
    "type": "number",
    "default": 0.75,
    "description": "Shapes broad ocean basins and coherent landmasses (Earth-like hypsometry).",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "sunAzimuth": {
    "domain": "planet",
    "group": "Lighting",
    "label": "Sun azimuth",
    "type": "number",
    "default": 100,
    "description": "Degrees (3/4 light from the default camera)",
    "min": 0,
    "max": 360,
    "step": 1
  },
  "sunElevation": {
    "domain": "planet",
    "group": "Lighting",
    "label": "Sun elevation",
    "type": "number",
    "default": 18,
    "description": "Sun elevation",
    "min": -30,
    "max": 90,
    "step": 1
  },
  "sunIntensity": {
    "domain": "planet",
    "group": "Lighting",
    "label": "Sun intensity",
    "type": "number",
    "default": 1,
    "description": "Sun intensity",
    "min": 0.2,
    "max": 2.5,
    "step": 0.05
  },
  "ambient": {
    "domain": "planet",
    "group": "Lighting",
    "label": "Sky light",
    "type": "number",
    "default": 0.25,
    "description": "Sky light strength — Diffuse light from the sky dome (fades out on the night side)",
    "min": 0,
    "max": 0.8,
    "step": 0.02
  },
  "exposure": {
    "domain": "planet",
    "group": "Lighting",
    "label": "Exposure",
    "type": "number",
    "default": 1,
    "description": "Camera exposure before the filmic tone map",
    "min": 0.3,
    "max": 3,
    "step": 0.05
  },
  "toonEnabled": {
    "domain": "planet",
    "group": "Stylized shading",
    "label": "Toon bands",
    "type": "boolean",
    "default": false,
    "description": "Optional cartoon banding of the sun term"
  },
  "toonBands": {
    "domain": "planet",
    "group": "Stylized shading",
    "label": "Bands",
    "type": "number",
    "default": 4,
    "description": "Bands",
    "min": 2,
    "max": 8,
    "step": 1
  },
  "toonSoftness": {
    "domain": "planet",
    "group": "Stylized shading",
    "label": "Band softness",
    "type": "number",
    "default": 0.06,
    "description": "Band softness",
    "min": 0,
    "max": 0.3,
    "step": 0.005
  },
  "bandSoftness": {
    "domain": "planet",
    "group": "Surface palette",
    "label": "Biome blend",
    "type": "number",
    "default": 0.05,
    "description": "Biome transition width — Width of the transitions between biomes",
    "min": 0.005,
    "max": 0.2,
    "step": 0.005
  },
  "snowLine": {
    "domain": "planet",
    "group": "Snow & poles",
    "label": "Snow line",
    "type": "number",
    "default": 0.62,
    "description": "0..1 height above sea where snow starts (equator) — Altitude where snow starts at the equator (drops toward the poles)",
    "min": 0.1,
    "max": 1.2,
    "step": 0.02
  },
  "polarCaps": {
    "domain": "planet",
    "group": "Snow & poles",
    "label": "Polar ice",
    "type": "number",
    "default": 0.55,
    "description": "0..1 extent of polar ice (land + sea ice) — Extent of the polar ice sheets and sea ice",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "biomeAmount": {
    "domain": "planet",
    "group": "Climate",
    "label": "Biome amount",
    "type": "number",
    "default": 1,
    "description": "0 = plain altitude ramp, 1 = full biome map",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "tempBias": {
    "domain": "planet",
    "group": "Climate",
    "label": "Temperature",
    "type": "number",
    "default": 0,
    "description": "-1 frozen .. +1 scorching — Shifts the whole planet colder or hotter",
    "min": -1,
    "max": 1,
    "step": 0.05
  },
  "moistureScale": {
    "domain": "planet",
    "group": "Climate",
    "label": "Moisture scale",
    "type": "number",
    "default": 2,
    "description": "Frequency of the moisture field",
    "min": 0.5,
    "max": 5,
    "step": 0.1
  },
  "bioTundra": {
    "domain": "planet",
    "group": "Cold biomes",
    "label": "Tundra (dry)",
    "type": "color",
    "default": [
      0.5,
      0.48,
      0.41
    ],
    "description": "Cold + dry biome colour (sRGB albedo)."
  },
  "bioSteppe": {
    "domain": "planet",
    "group": "Cold biomes",
    "label": "Steppe (mid)",
    "type": "color",
    "default": [
      0.53,
      0.51,
      0.35
    ],
    "description": "Cold + mid-moisture biome colour (sRGB albedo)."
  },
  "bioTaiga": {
    "domain": "planet",
    "group": "Cold biomes",
    "label": "Taiga (wet)",
    "type": "color",
    "default": [
      0.15,
      0.22,
      0.14
    ],
    "description": "Cold + wet biome colour (sRGB albedo)."
  },
  "bioShrub": {
    "domain": "planet",
    "group": "Temperate biomes",
    "label": "Shrubland (dry)",
    "type": "color",
    "default": [
      0.56,
      0.5,
      0.34
    ],
    "description": "Temperate + dry biome colour (sRGB albedo)."
  },
  "bioDesert": {
    "domain": "planet",
    "group": "Hot biomes",
    "label": "Desert (dry)",
    "type": "color",
    "default": [
      0.82,
      0.68,
      0.48
    ],
    "description": "Hot + dry biome colour (sRGB albedo)."
  },
  "bioSavanna": {
    "domain": "planet",
    "group": "Hot biomes",
    "label": "Savanna (mid)",
    "type": "color",
    "default": [
      0.56,
      0.5,
      0.28
    ],
    "description": "Hot + mid-moisture biome colour (sRGB albedo)."
  },
  "bioJungle": {
    "domain": "planet",
    "group": "Hot biomes",
    "label": "Jungle (wet)",
    "type": "color",
    "default": [
      0.09,
      0.19,
      0.07
    ],
    "description": "Hot + wet biome colour (sRGB albedo)."
  },
  "colDeep": {
    "domain": "planet",
    "group": "Ocean",
    "label": "Deep water",
    "type": "color",
    "default": [
      0.02,
      0.075,
      0.17
    ],
    "description": "Deep-water body colour (scattering)"
  },
  "colShallow": {
    "domain": "planet",
    "group": "Ocean",
    "label": "Shallow tint",
    "type": "color",
    "default": [
      0.3,
      0.74,
      0.74
    ],
    "description": "Tint after one clarity depth of water"
  },
  "colSand": {
    "domain": "planet",
    "group": "Surface palette",
    "label": "Sand",
    "type": "color",
    "default": [
      0.78,
      0.71,
      0.56
    ],
    "description": "Beach / low coast colour (sRGB albedo)."
  },
  "colGrass": {
    "domain": "planet",
    "group": "Temperate biomes",
    "label": "Grassland (mid)",
    "type": "color",
    "default": [
      0.33,
      0.4,
      0.19
    ],
    "description": "Temperate grassland colour (sRGB albedo)."
  },
  "colForest": {
    "domain": "planet",
    "group": "Temperate biomes",
    "label": "Forest (wet)",
    "type": "color",
    "default": [
      0.15,
      0.24,
      0.11
    ],
    "description": "Temperate forest colour (sRGB albedo)."
  },
  "colRock": {
    "domain": "planet",
    "group": "Surface palette",
    "label": "Rock",
    "type": "color",
    "default": [
      0.42,
      0.38,
      0.34
    ],
    "description": "Bare rock / cliff colour (sRGB albedo)."
  },
  "colSnow": {
    "domain": "planet",
    "group": "Surface palette",
    "label": "Snow & ice",
    "type": "color",
    "default": [
      0.93,
      0.95,
      0.97
    ],
    "description": "Snow and ice colour (sRGB albedo)."
  },
  "colFoam": {
    "domain": "planet",
    "group": "Foam",
    "label": "Foam",
    "type": "color",
    "default": [
      0.92,
      0.95,
      0.96
    ],
    "description": "Surf foam / sea ice crust colour (sRGB albedo)."
  },
  "waterEnabled": {
    "domain": "planet",
    "group": "Ocean",
    "label": "Ocean",
    "type": "boolean",
    "default": true,
    "description": "Render the ocean."
  },
  "waterOpacity": {
    "domain": "planet",
    "group": "Water",
    "label": "waterOpacity",
    "type": "number",
    "default": 0.78,
    "description": "Export-only (glTF ocean shell)"
  },
  "waterClarity": {
    "domain": "planet",
    "group": "Ocean",
    "label": "Clarity",
    "type": "number",
    "default": 0.07,
    "description": "Clarity depth, fraction of heightScale — How deep light reaches before the water takes the shallow tint (fraction of the terrain relief)",
    "min": 0.005,
    "max": 0.4,
    "step": 0.005
  },
  "waveSize": {
    "domain": "planet",
    "group": "Waves",
    "label": "Wave size",
    "type": "number",
    "default": 6,
    "description": "Longest wavelength, world units",
    "min": 0.5,
    "max": 40,
    "step": 0.5
  },
  "waveHeight": {
    "domain": "planet",
    "group": "Waves",
    "label": "Wave height",
    "type": "number",
    "default": 0.8,
    "description": "Wave steepness / roughness — Steepness: calm mirror to rough sea",
    "min": 0,
    "max": 2,
    "step": 0.05
  },
  "waveSpeed": {
    "domain": "planet",
    "group": "Waves",
    "label": "Wave speed",
    "type": "number",
    "default": 1,
    "description": "Wave animation speed.",
    "min": 0,
    "max": 3,
    "step": 0.05
  },
  "waterSpec": {
    "domain": "planet",
    "group": "Ocean",
    "label": "Sun glint",
    "type": "number",
    "default": 1,
    "description": "Sun glint strength",
    "min": 0,
    "max": 2,
    "step": 0.05
  },
  "foamWidth": {
    "domain": "planet",
    "group": "Foam",
    "label": "Shore width",
    "type": "number",
    "default": 0.25,
    "description": "Shore foam band (depth-based) — Surf band along the coasts (depth based)",
    "min": 0,
    "max": 1,
    "step": 0.01
  },
  "foamAmount": {
    "domain": "planet",
    "group": "Foam",
    "label": "Amount",
    "type": "number",
    "default": 1,
    "description": "Overall foam strength (shore + whitecaps).",
    "min": 0,
    "max": 2,
    "step": 0.05
  },
  "whitecaps": {
    "domain": "planet",
    "group": "Foam",
    "label": "Whitecaps",
    "type": "number",
    "default": 0.3,
    "description": "Breaking crests in windy open water",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "waterEmissive": {
    "domain": "planet",
    "group": "Ocean",
    "label": "Molten",
    "type": "number",
    "default": 0,
    "description": "1 = molten (lava seas) — Self-lit liquid (lava seas); foam becomes cooled crust",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "cloudsEnabled": {
    "domain": "planet",
    "group": "Clouds",
    "label": "Clouds",
    "type": "boolean",
    "default": true,
    "description": "Render the volumetric cloud layer (and its shadows)."
  },
  "cloudCoverage": {
    "domain": "planet",
    "group": "Clouds",
    "label": "Coverage",
    "type": "number",
    "default": 0.45,
    "description": "Fraction of the sky covered by clouds.",
    "min": 0,
    "max": 1,
    "step": 0.02
  },
  "cloudSoftness": {
    "domain": "planet",
    "group": "Clouds",
    "label": "Softness",
    "type": "number",
    "default": 0.18,
    "description": "Width of the coverage falloff (wispy edges) — How gradually systems thin out into broken fields",
    "min": 0.01,
    "max": 0.5,
    "step": 0.01
  },
  "cloudDensity": {
    "domain": "planet",
    "group": "Clouds",
    "label": "Density",
    "type": "number",
    "default": 0.8,
    "description": "Optical thickness",
    "min": 0.1,
    "max": 2,
    "step": 0.05
  },
  "cloudScale": {
    "domain": "planet",
    "group": "Shape & motion",
    "label": "System scale",
    "type": "number",
    "default": 3.2,
    "description": "Weather-system frequency — Frequency of weather systems",
    "min": 1,
    "max": 10,
    "step": 0.1
  },
  "cloudDetail": {
    "domain": "planet",
    "group": "Shape & motion",
    "label": "Erosion",
    "type": "number",
    "default": 0.7,
    "description": "Erosion strength — Wispy bottoms / billowy tops",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "cloudDetailScale": {
    "domain": "planet",
    "group": "Shape & motion",
    "label": "Billow size",
    "type": "number",
    "default": 1,
    "description": "Size of the billows",
    "min": 0.3,
    "max": 3,
    "step": 0.05
  },
  "cloudAltitude": {
    "domain": "planet",
    "group": "Shape & motion",
    "label": "Altitude",
    "type": "number",
    "default": 0.004,
    "description": "Cloud base above sea level, fraction of radius",
    "min": 0,
    "max": 0.03,
    "step": 0.001
  },
  "cloudThickness": {
    "domain": "planet",
    "group": "Shape & motion",
    "label": "Thickness",
    "type": "number",
    "default": 0.009,
    "description": "Shell thickness, fraction of radius — Depth of the cloud layer (fraction of radius)",
    "min": 0.002,
    "max": 0.03,
    "step": 0.001
  },
  "cloudSpeed": {
    "domain": "planet",
    "group": "Shape & motion",
    "label": "Speed",
    "type": "number",
    "default": 0.6,
    "description": "Cloud drift / evolution speed.",
    "min": 0,
    "max": 3,
    "step": 0.05
  },
  "cloudShadowStrength": {
    "domain": "planet",
    "group": "Clouds",
    "label": "Shadows",
    "type": "number",
    "default": 0.6,
    "description": "Darkness of the shadows clouds cast on the ground and sea.",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "cloudQuality": {
    "domain": "planet",
    "group": "Quality",
    "label": "Ray steps",
    "type": "number",
    "default": 64,
    "description": "Max raymarch steps — Maximum raymarch steps through the cloud layer",
    "min": 24,
    "max": 128,
    "step": 4
  },
  "cloudResolution": {
    "domain": "planet",
    "group": "Quality",
    "label": "Resolution",
    "type": "number",
    "default": 0.5,
    "description": "Cloud pass resolution scale — Pixel budget of the cloud pass when the planet fills the screen — a smaller planet automatically gets full-resolution clouds",
    "min": 0.25,
    "max": 1,
    "step": 0.05
  },
  "cloudColor": {
    "domain": "planet",
    "group": "Colors",
    "label": "Cloud",
    "type": "color",
    "default": [
      1,
      1,
      1
    ],
    "description": "Sunlit cloud tint (sRGB)."
  },
  "cloudShadow": {
    "domain": "planet",
    "group": "Colors",
    "label": "Sky-lit tint",
    "type": "color",
    "default": [
      0.78,
      0.84,
      0.95
    ],
    "description": "Ambient (sky-lit) tint"
  },
  "atmoEnabled": {
    "domain": "planet",
    "group": "Atmosphere",
    "label": "Atmosphere",
    "type": "boolean",
    "default": true,
    "description": "Render atmospheric scattering."
  },
  "atmoColor": {
    "domain": "planet",
    "group": "Atmosphere",
    "label": "Scattering tint",
    "type": "color",
    "default": [
      0.35,
      0.6,
      1
    ],
    "description": "Rayleigh tint (blue = Earth)"
  },
  "atmoStrength": {
    "domain": "planet",
    "group": "Atmosphere",
    "label": "Density",
    "type": "number",
    "default": 1,
    "description": "Air density — Air density — 1 matches Earth's optical depth at any planet size",
    "min": 0,
    "max": 3,
    "step": 0.05
  },
  "atmoHeight": {
    "domain": "planet",
    "group": "Atmosphere",
    "label": "Height",
    "type": "number",
    "default": 0.045,
    "description": "Thickness, fraction of radius — Atmosphere thickness as a fraction of the radius",
    "min": 0.01,
    "max": 0.12,
    "step": 0.005
  },
  "atmoHaze": {
    "domain": "planet",
    "group": "Atmosphere",
    "label": "Haze",
    "type": "number",
    "default": 0.3,
    "description": "Aerosols / dust (Mie)",
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "chunkRes": {
    "domain": "planet",
    "group": "LOD",
    "label": "Chunk res",
    "type": "number",
    "default": 32,
    "description": "Grid quads per chunk side (rebuild)",
    "min": 8,
    "max": 64,
    "step": 8,
    "structural": true
  },
  "maxDepth": {
    "domain": "planet",
    "group": "LOD",
    "label": "Max depth",
    "type": "number",
    "default": 5,
    "description": "Quadtree depth (rebuild) — Quadtree subdivision limit (rebuild)",
    "min": 2,
    "max": 7,
    "step": 1,
    "structural": true
  },
  "splitFactor": {
    "domain": "planet",
    "group": "LOD",
    "label": "Split factor",
    "type": "number",
    "default": 2.4,
    "description": "Split when camDist < size * factor — Higher = subdivide sooner (more detail, more chunks)",
    "min": 1.2,
    "max": 4,
    "step": 0.1
  },
  "wireframe": {
    "domain": "planet",
    "group": "Debug",
    "label": "Wireframe",
    "type": "boolean",
    "default": false,
    "description": "Draw the terrain LOD chunks as wireframe (debug)."
  }
};
