// GENERATED by scripts/gen-param-docs.mjs — do not edit by hand.

/** sRGB colour: [r, g, b] in 0..1, '#rrggbb', 0xrrggbb or a THREE.Color. */
export type ColorInput = [number, number, number] | string | number | import('three').Color;

/** Every Planet parameter (all optional when passed in; see docs/parameters.md). */
export interface PlanetParams {
  /** Body type: 'planet' (terrestrial), 'gas' or 'star'. Prefer the Planet `type` option. Default: 'planet'. */
  mode?: 'planet' | 'gas' | 'star';
  /** Look-model version of the parameter set (used to migrate old studio projects). Leave as is. Default: 3. */
  renderVersion?: number;
  /** Effective temperature (K) — the Sun Range 2000..30000. Default: 5772. */
  starTemperature?: number;
  /** Artistic filter over the blackbody colour: a real 5772 K disc is a pale peach-white on screen; this warms it toward the familiar golden Sun Default: [1, 0.98, 0.7]. */
  starTint?: ColorInput;
  /** Emitted radiance (drives glare / bloom) Range 0.2..5. Default: 1. */
  starBrightness?: number;
  /** Granulation scale — Size of the convection cells (larger = smaller cells) Range 0.5..8. Default: 3. */
  starNoiseScale?: number;
  /** Supergranulation network / mottling Range 0..1.5. Default: 0.6. */
  starTurbulence?: number;
  /** Granulation contrast — Contrast between bright cells and dark lanes Range 0..1.5. Default: 0.9. */
  starGranules?: number;
  /** Convection + rotation speed Range 0..3. Default: 1. */
  starFlowSpeed?: number;
  /** Bright network toward the limb — Bright magnetic network, strongest toward the limb Range 0..1.5. Default: 0.8. */
  starFaculae?: number;
  /** Render sunspots. Default: true. */
  starSpotsEnabled?: boolean;
  /** Sunspot coverage — Magnetic activity: spot coverage in the active belts Range 0..1. Default: 0.4. */
  starSpots?: number;
  /** Active-region size (frequency) — Frequency of the active regions (larger = smaller groups) Range 0.5..8. Default: 2.4. */
  starSpotScale?: number;
  /** 1 = solar limb darkening — 1 = solar; the limb also reddens Range 0..1.5. Default: 1. */
  starLimbDarken?: number;
  /** Glare / bloom strength — Glare spreading from the overexposed disc Range 0..3. Default: 1. */
  starBloom?: number;
  /** Radius breathing (pulsating variables) Range 0..0.08. Default: 0. */
  starPulseAmount?: number;
  /** Speed of the radius breathing (starPulseAmount). Range 0..4. Default: 1.2. */
  starPulseSpeed?: number;
  /** Render the corona / streamers around the disc. Default: true. */
  starCoronaEnabled?: boolean;
  /** Corona Default: [1, 0.94, 0.86]. */
  starCoronaColor?: ColorInput;
  /** Halo extent (fraction of radius) — Extent of the outer corona Range 0..1.5. Default: 0.6. */
  starCoronaSize?: number;
  /** Strength Range 0..2. Default: 0.6. */
  starCoronaStrength?: number;
  /** Streamer contrast in the corona — Contrast of the radial streamers Range 0..1.5. Default: 0.7. */
  starFlares?: number;
  /** Limb prominences — Glowing plasma loops rising off the limb Range 0..1.5. Default: 0.5. */
  starProminences?: number;
  /** H-alpha chromosphere / prominences Default: [1, 0.3, 0.22]. */
  starChromoColor?: ColorInput;
  /** Belts + zones, pole to pole Range 2..32. Default: 18. */
  gasBandCount?: number;
  /** Belt / zone contrast — Brightness difference between dark belts and bright zones Range 0..1. Default: 0.6. */
  gasContrast?: number;
  /** Band edge waviness — How much the band edges meander Range 0..1.5. Default: 0.5. */
  gasBandWarp?: number;
  /** Eddy turbulence in the shear zones — Eddies in the shear zones between belts and zones Range 0..1.5. Default: 0.75. */
  gasWarp?: number;
  /** Eddy size (frequency) — Frequency of the turbulent eddies Range 0.8..8. Default: 3. */
  gasScale?: number;
  /** Jet + churn speed — Zonal jet + churn speed Range 0..3. Default: 1. */
  gasFlowSpeed?: number;
  /** Polar region extent / haze — Banding dissolves into cyclones under a haze toward the poles Range 0..1. Default: 0.55. */
  gasPolarHaze?: number;
  /** Minnaert limb darkening Range 0..1. Default: 0.5. */
  gasLimb?: number;
  /** Axial tilt (degrees) — Tilt of the spin axis (and the ring plane), degrees Range 0..90. Default: 8. */
  gasTilt?: number;
  /** Render the great spot and the small storm ovals. Default: true. */
  gasStormsEnabled?: boolean;
  /** Great storm size (0 = none) — Size of the giant anticyclone (0 = none) Range 0..1. Default: 0.65. */
  gasGreatSpot?: number;
  /** Small oval count — Number of smaller vortices (white ovals, dark barges) Range 0..1. Default: 0.5. */
  gasStorms?: number;
  /** Small oval size Range 0.3..3. Default: 1. */
  gasStormScale?: number;
  /** Bright zone colour (sRGB albedo). Default: [0.82, 0.74, 0.6]. */
  gasColorZone?: ColorInput;
  /** Dark belt colour (sRGB albedo). Default: [0.56, 0.4, 0.29]. */
  gasColorBelt?: ColorInput;
  /** Turbulent eddy accent colour (sRGB albedo). Default: [0.68, 0.38, 0.23]. */
  gasColorAccent?: ColorInput;
  /** Storm / great spot colour (sRGB albedo). Default: [0.7, 0.33, 0.2]. */
  gasColorStorm?: ColorInput;
  /** Polar region colour (sRGB albedo). Default: [0.52, 0.53, 0.56]. */
  gasColorPolar?: ColorInput;
  /** High haze Rayleigh tint Default: [0.55, 0.68, 1]. */
  gasAtmoColor?: ColorInput;
  /** Air above the cloud tops Range 0..2. Default: 0.15. */
  gasAtmoStrength?: number;
  /** Aerosol haze (Mie) Range 0..1. Default: 0.5. */
  gasAtmoHaze?: number;
  /** Render the ring system. Default: false. */
  gasRingsEnabled?: boolean;
  /** X radius — Inner edge, in planet radii Range 1.05..3. Default: 1.25. */
  gasRingInner?: number;
  /** Outer edge, in planet radii Range 1.2..4. Default: 2.25. */
  gasRingOuter?: number;
  /** Optical depth scale Range 0..2. Default: 1. */
  gasRingOpacity?: number;
  /** Ring particle colour (sRGB albedo). Default: [0.86, 0.8, 0.69]. */
  gasRingColor?: ColorInput;
  /** Random seed: every procedural field (terrain, clouds, bands, spots) derives from it. Default: 1337. */
  seed?: number;
  /** Planet radius in local units (world units at scale 1). Range 600..6000. Default: 2000. */
  radius?: number;
  /** Terrain relief: height of the highest peaks above the base radius, in local units. Range 20..400. Default: 80. */
  heightScale?: number;
  /** Sea level, as a fraction of heightScale above the base radius. Range 0..0.9. Default: 0.42. */
  seaLevel?: number;
  /** Base frequency of the continent noise (higher = more, smaller landmasses). Range 0.5..8. Default: 2.6. */
  noiseScale?: number;
  /** Compile-time define (material rebuild) — Rebuilds the shaders Range 3..8. Default: 6. */
  octaves?: number;
  /** Amplitude falloff between noise octaves (higher = rougher terrain). Range 0.3..0.7. Default: 0.52. */
  persistence?: number;
  /** Frequency step between noise octaves. Range 1.5..3. Default: 2.05. */
  lacunarity?: number;
  /** Domain warp strength: folds and twists coastlines and ranges. Range 0..2. Default: 0.65. */
  warp?: number;
  /** Strength of the ridged mountain ranges along tectonic belts. Range 0..1.5. Default: 0.55. */
  ridge?: number;
  /** Frequency of the mountain ridges. Range 1..6. Default: 2.4. */
  mountainScale?: number;
  /** Impact crater amount (0 = none). Range 0..1. Default: 0. */
  craters?: number;
  /** Crater frequency (higher = smaller craters). Range 2..16. Default: 6. */
  craterScale?: number;
  /** Shapes broad ocean basins and coherent landmasses (Earth-like hypsometry). Range 0..1. Default: 0.75. */
  continents?: number;
  /** Degrees (3/4 light from the default camera) Range 0..360. Default: 100. */
  sunAzimuth?: number;
  /** Sun elevation Range -30..90. Default: 18. */
  sunElevation?: number;
  /** Sun intensity Range 0.2..2.5. Default: 1. */
  sunIntensity?: number;
  /** Sky light strength — Diffuse light from the sky dome (fades out on the night side) Range 0..0.8. Default: 0.25. */
  ambient?: number;
  /** Camera exposure before the filmic tone map Range 0.3..3. Default: 1. */
  exposure?: number;
  /** Optional cartoon banding of the sun term Default: false. */
  toonEnabled?: boolean;
  /** Bands Range 2..8. Default: 4. */
  toonBands?: number;
  /** Band softness Range 0..0.3. Default: 0.06. */
  toonSoftness?: number;
  /** Biome transition width — Width of the transitions between biomes Range 0.005..0.2. Default: 0.05. */
  bandSoftness?: number;
  /** 0..1 height above sea where snow starts (equator) — Altitude where snow starts at the equator (drops toward the poles) Range 0.1..1.2. Default: 0.62. */
  snowLine?: number;
  /** 0..1 extent of polar ice (land + sea ice) — Extent of the polar ice sheets and sea ice Range 0..1. Default: 0.55. */
  polarCaps?: number;
  /** 0 = plain altitude ramp, 1 = full biome map Range 0..1. Default: 1. */
  biomeAmount?: number;
  /** -1 frozen .. +1 scorching — Shifts the whole planet colder or hotter Range -1..1. Default: 0. */
  tempBias?: number;
  /** Frequency of the moisture field Range 0.5..5. Default: 2. */
  moistureScale?: number;
  /** Cold + dry biome colour (sRGB albedo). Default: [0.5, 0.48, 0.41]. */
  bioTundra?: ColorInput;
  /** Cold + mid-moisture biome colour (sRGB albedo). Default: [0.53, 0.51, 0.35]. */
  bioSteppe?: ColorInput;
  /** Cold + wet biome colour (sRGB albedo). Default: [0.15, 0.22, 0.14]. */
  bioTaiga?: ColorInput;
  /** Temperate + dry biome colour (sRGB albedo). Default: [0.56, 0.5, 0.34]. */
  bioShrub?: ColorInput;
  /** Hot + dry biome colour (sRGB albedo). Default: [0.82, 0.68, 0.48]. */
  bioDesert?: ColorInput;
  /** Hot + mid-moisture biome colour (sRGB albedo). Default: [0.56, 0.5, 0.28]. */
  bioSavanna?: ColorInput;
  /** Hot + wet biome colour (sRGB albedo). Default: [0.09, 0.19, 0.07]. */
  bioJungle?: ColorInput;
  /** Deep-water body colour (scattering) Default: [0.02, 0.075, 0.17]. */
  colDeep?: ColorInput;
  /** Tint after one clarity depth of water Default: [0.3, 0.74, 0.74]. */
  colShallow?: ColorInput;
  /** Beach / low coast colour (sRGB albedo). Default: [0.78, 0.71, 0.56]. */
  colSand?: ColorInput;
  /** Temperate grassland colour (sRGB albedo). Default: [0.33, 0.4, 0.19]. */
  colGrass?: ColorInput;
  /** Temperate forest colour (sRGB albedo). Default: [0.15, 0.24, 0.11]. */
  colForest?: ColorInput;
  /** Bare rock / cliff colour (sRGB albedo). Default: [0.42, 0.38, 0.34]. */
  colRock?: ColorInput;
  /** Snow and ice colour (sRGB albedo). Default: [0.93, 0.95, 0.97]. */
  colSnow?: ColorInput;
  /** Surf foam / sea ice crust colour (sRGB albedo). Default: [0.92, 0.95, 0.96]. */
  colFoam?: ColorInput;
  /** Render the ocean. Default: true. */
  waterEnabled?: boolean;
  /** Export-only (glTF ocean shell) Default: 0.78. */
  waterOpacity?: number;
  /** Clarity depth, fraction of heightScale — How deep light reaches before the water takes the shallow tint (fraction of the terrain relief) Range 0.005..0.4. Default: 0.07. */
  waterClarity?: number;
  /** Longest wavelength, world units Range 0.5..40. Default: 6. */
  waveSize?: number;
  /** Wave steepness / roughness — Steepness: calm mirror to rough sea Range 0..2. Default: 0.8. */
  waveHeight?: number;
  /** Wave animation speed. Range 0..3. Default: 1. */
  waveSpeed?: number;
  /** Sun glint strength Range 0..2. Default: 1. */
  waterSpec?: number;
  /** Shore foam band (depth-based) — Surf band along the coasts (depth based) Range 0..1. Default: 0.25. */
  foamWidth?: number;
  /** Overall foam strength (shore + whitecaps). Range 0..2. Default: 1. */
  foamAmount?: number;
  /** Breaking crests in windy open water Range 0..1. Default: 0.3. */
  whitecaps?: number;
  /** 1 = molten (lava seas) — Self-lit liquid (lava seas); foam becomes cooled crust Range 0..1. Default: 0. */
  waterEmissive?: number;
  /** Render the volumetric cloud layer (and its shadows). Default: true. */
  cloudsEnabled?: boolean;
  /** Fraction of the sky covered by clouds. Range 0..1. Default: 0.45. */
  cloudCoverage?: number;
  /** Width of the coverage falloff (wispy edges) — How gradually systems thin out into broken fields Range 0.01..0.5. Default: 0.18. */
  cloudSoftness?: number;
  /** Optical thickness Range 0.1..2. Default: 0.8. */
  cloudDensity?: number;
  /** Weather-system frequency — Frequency of weather systems Range 1..10. Default: 3.2. */
  cloudScale?: number;
  /** Erosion strength — Wispy bottoms / billowy tops Range 0..1. Default: 0.7. */
  cloudDetail?: number;
  /** Size of the billows Range 0.3..3. Default: 1. */
  cloudDetailScale?: number;
  /** Cloud base above sea level, fraction of radius Range 0..0.03. Default: 0.004. */
  cloudAltitude?: number;
  /** Shell thickness, fraction of radius — Depth of the cloud layer (fraction of radius) Range 0.002..0.03. Default: 0.009. */
  cloudThickness?: number;
  /** Cloud drift / evolution speed. Range 0..3. Default: 0.6. */
  cloudSpeed?: number;
  /** Darkness of the shadows clouds cast on the ground and sea. Range 0..1. Default: 0.6. */
  cloudShadowStrength?: number;
  /** Max raymarch steps — Maximum raymarch steps through the cloud layer Range 24..128. Default: 64. */
  cloudQuality?: number;
  /** Cloud pass resolution scale — Pixel budget of the cloud pass when the planet fills the screen — a smaller planet automatically gets full-resolution clouds Range 0.25..1. Default: 0.5. */
  cloudResolution?: number;
  /** Sunlit cloud tint (sRGB). Default: [1, 1, 1]. */
  cloudColor?: ColorInput;
  /** Ambient (sky-lit) tint Default: [0.78, 0.84, 0.95]. */
  cloudShadow?: ColorInput;
  /** Render atmospheric scattering. Default: true. */
  atmoEnabled?: boolean;
  /** Rayleigh tint (blue = Earth) Default: [0.35, 0.6, 1]. */
  atmoColor?: ColorInput;
  /** Air density — Air density — 1 matches Earth's optical depth at any planet size Range 0..3. Default: 1. */
  atmoStrength?: number;
  /** Thickness, fraction of radius — Atmosphere thickness as a fraction of the radius Range 0.01..0.12. Default: 0.045. */
  atmoHeight?: number;
  /** Aerosols / dust (Mie) Range 0..1. Default: 0.3. */
  atmoHaze?: number;
  /** Grid quads per chunk side (rebuild) Range 8..64. Default: 32. */
  chunkRes?: number;
  /** Quadtree depth (rebuild) — Quadtree subdivision limit (rebuild) Range 2..7. Default: 5. */
  maxDepth?: number;
  /** Split when camDist < size * factor — Higher = subdivide sooner (more detail, more chunks) Range 1.2..4. Default: 2.4. */
  splitFactor?: number;
  /** Draw the terrain LOD chunks as wireframe (debug). Default: false. */
  wireframe?: boolean;
}

/** Parameter object as stored on a Planet (colours normalised to arrays). */
export type ResolvedPlanetParams = {
  [K in keyof PlanetParams]-?: PlanetParams[K] extends ColorInput | undefined
    ? (Exclude<PlanetParams[K], undefined> extends ColorInput ? [number, number, number] : Exclude<PlanetParams[K], undefined>)
    : Exclude<PlanetParams[K], undefined>;
};
